/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KanbanBoard: typeof import('./components/KanbanBoard.vue')['default']
    KanbanCard: typeof import('./components/KanbanCard.vue')['default']
    KanbanColumn: typeof import('./components/KanbanColumn.vue')['default']
    KanbanDeleteButton: typeof import('./components/KanbanDeleteButton.vue')['default']
    KanbanForm: typeof import('./components/KanbanForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
